name: Test

on: pull_request

env:
  NODE_VERSION: "16"

jobs:
  install_dependancies:
    name: Install Dependancies

    runs-on: ubuntu-latest

    timeout-minutes: 10
    
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}
          
      - name: Checkout the repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Setup Node
        uses: actions/setup-node@v2.1.5
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Cache Node npm
        uses: actions/cache@v2
        with:
          path: assets/node_modules
          key: ${{ runner.os }}-crit-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-crit-node-

      - name: Install dependencies
        run: npm install

  lint_codebase:
    name: Linting

    needs: install_dependancies

    runs-on: ubuntu-latest

    timeout-minutes: 10

    steps: 
      - name: Checkout the repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Setup Node
        uses: actions/setup-node@v2.1.5
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Cache Node npm
        uses: actions/cache@v2
        with:
          path: node_modules/
          key: ${{ runner.os }}-crit-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-crit-node-

      - name: Install dependencies
        run: npm install

      - name: Run linter
        run: npm run lint

  unit_test:
    name: Run Unit tests

    needs: install_dependancies

    runs-on: ubuntu-latest

    timeout-minutes: 15

    steps: 
      - name: Checkout the repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Setup Node
        uses: actions/setup-node@v2.1.5
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Cache Node npm
        uses: actions/cache@v2
        with:
          path: node_modules/
          key: ${{ runner.os }}-crit-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-crit-node-

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Upload Test Artifacts
        uses: actions/upload-artifact@v2
        if: ${{ failure() }}
        with:
          name: coverage
          path: coverage/

  ui_test:
    name: Run UI tests

    needs: install_dependancies

    runs-on: ubuntu-latest

    timeout-minutes: 20

    steps: 
      - name: Checkout the repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Setup Node
        uses: actions/setup-node@v2.1.5
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Cache Node npm
        uses: actions/cache@v2
        with:
          path: node_modules/
          key: ${{ runner.os }}-crit-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-crit-node-

      - name: Install dependencies
        run: npm install

      - name: Run application in background
        run: npx serve -s build -l 3000 &

      - name: Run tests
        run: npm run cypress:run

      - name: Upload Test Artifacts
        uses: actions/upload-artifact@v2
        if: ${{ failure() }}
        with:
          name: cypress
          path: cypress/videos/
